services:
  saolsen_connect4_rand:
    build:
      context: .
      dockerfile: docker/saolsen_connect4_rand.Dockerfile
    environment:
        - PORT=80
  gameplay:
    build:
      context: .
      dockerfile: docker/gameplay.Dockerfile
    depends_on:
      - saolsen_connect4_rand
